version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.6.13
        environment:
          NLTK_DATA: /root/nltk_data
    steps:
      - checkout
      - run:
          command: |
            sudo python -m venv env
            . env/bin/activate
            sudo python -m pip install -r requirements_dev.txt
            sudo python -m textblob.download_corpora
            sudo pytest

workflows:
  main:
    jobs:
      - test
