version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9.4
        environment:
          NLTK_DATA: /root/nltk_data
    steps:
      - checkout
      - run:
          command: |
            python -m venv env
            . env/bin/activate
            python -m pip install -r requirements_dev.txt
            python -m textblob.download_corpora
            pytest

workflows:
  main:
    jobs:
      - test
